# Answer.create!([
#   {question_id: 1, content: "120 m", is_correct: false},
#   {question_id: 1, content: "199 m", is_correct: false},
#   {question_id: 1, content: "324 m", is_correct: true},
#   {question_id: 1, content: "404 m", is_correct: false},
#   {question_id: 2, content: "Lyon", is_correct: false},
#   {question_id: 2, content: "Paryż", is_correct: true},
#   {question_id: 2, content: "Nicea", is_correct: false},
#   {question_id: 2, content: "Bruksela", is_correct: false},
#   {question_id: 3, content: "Loara", is_correct: false},
#   {question_id: 3, content: "Sekwana", is_correct: true},
#   {question_id: 3, content: "Tamiza", is_correct: false},
#   {question_id: 3, content: "Ren", is_correct: false},
#   {question_id: 4, content: "niebieski, biały, czerwony ", is_correct: true},
#   {question_id: 4, content: "niebieski, żółty, czerwony", is_correct: false},
#   {question_id: 4, content: "czerwony, niebieski", is_correct: false},
#   {question_id: 4, content: "czerwony, niebieski, zielony", is_correct: false},
#   {question_id: 5, content: "Mont Posets – 3375 m n.p.m.", is_correct: false},
#   {question_id: 5, content: "Mont Blanc – 4810 m n.p.m.", is_correct: true},
#   {question_id: 5, content: "Grossglockner – 3798 m n.p.m.", is_correct: false},
#   {question_id: 5, content: "Matterhorn – 4478 m n.p.m.", is_correct: false},
#   {question_id: 8, content: "Internet Explorer", is_correct: false},
#   {question_id: 8, content: "Google", is_correct: true},
#   {question_id: 8, content: "Chrome", is_correct: false},
#   {question_id: 8, content: "Facebook", is_correct: false},
#   {question_id: 9, content: "Dziewczynka z Zapałkami", is_correct: false},
#   {question_id: 9, content: "Muminek", is_correct: false},
#   {question_id: 9, content: "Kubuś Puchatek", is_correct: true},
#   {question_id: 9, content: "Pszczółka Maja", is_correct: false},
#   {question_id: 10, content: "Nabrał wody w usta", is_correct: false},
#   {question_id: 10, content: "Poszedł po rozum do głowy", is_correct: true},
#   {question_id: 10, content: "Poszedł po olej do głowy", is_correct: false},
#   {question_id: 10, content: "Zadumał się", is_correct: false},
#   {question_id: 11, content: "Burak", is_correct: false},
#   {question_id: 11, content: "Pietruszka", is_correct: false},
#   {question_id: 11, content: "Marchewka", is_correct: true},
#   {question_id: 11, content: "Cebula", is_correct: false},
#   {question_id: 12, content: "966", is_correct: false},
#   {question_id: 12, content: "1025", is_correct: false},
#   {question_id: 12, content: "1410", is_correct: true},
#   {question_id: 12, content: "1421", is_correct: false},
#   {question_id: 13, content: "Adam Mickiewicz", is_correct: true},
#   {question_id: 13, content: "Czesław Miłosz", is_correct: false},
#   {question_id: 13, content: "Juliusz Słowacki", is_correct: false},
#   {question_id: 13, content: "Maria Konopnicka", is_correct: false},
#   {question_id: 14, content: "Zebra", is_correct: true},
#   {question_id: 14, content: "Tygrys", is_correct: false},
#   {question_id: 14, content: "Żyrafa", is_correct: false},
#   {question_id: 14, content: "Bawół", is_correct: false},
#   {question_id: 15, content: "Rysy", is_correct: true},
#   {question_id: 15, content: "Giewont", is_correct: false},
#   {question_id: 15, content: "Gerlach", is_correct: false},
#   {question_id: 15, content: "Śnieżka", is_correct: false},
#   {question_id: 16, content: "Volvo", is_correct: false},
#   {question_id: 16, content: "Mercedes", is_correct: true},
#   {question_id: 16, content: "Seat", is_correct: false},
#   {question_id: 16, content: "Toyota", is_correct: false},
#   {question_id: 17, content: "Nowy Jork", is_correct: false},
#   {question_id: 17, content: "Sydney", is_correct: false},
#   {question_id: 17, content: "San Francisco", is_correct: true},
#   {question_id: 17, content: "Londyn", is_correct: false},
#   {question_id: 18, content: "Ssaki", is_correct: false},
#   {question_id: 18, content: "Gady", is_correct: true},
#   {question_id: 18, content: "Płazy", is_correct: false},
#   {question_id: 18, content: "Krążkopławy", is_correct: false},
#   {question_id: 19, content: "Eukaliptus", is_correct: false},
#   {question_id: 19, content: "Banany", is_correct: false},
#   {question_id: 19, content: "Bambus", is_correct: true},
#   {question_id: 19, content: "Różnego rodzaju trawy i krzewy", is_correct: false},
#   {question_id: 20, content: "20 000 km", is_correct: false},
#   {question_id: 20, content: "35 100 km", is_correct: false},
#   {question_id: 20, content: "40 076 km", is_correct: true},
#   {question_id: 20, content: "42 076 km", is_correct: false},
#   {question_id: 21, content: "W Morzu Arabskim", is_correct: false},
#   {question_id: 21, content: "W Morzu Południowochińskim", is_correct: false},
#   {question_id: 21, content: "W Zatoce Bengalskiej", is_correct: false},
#   {question_id: 21, content: "W Morzu Żółtym", is_correct: true},
#   {question_id: 22, content: "Zaleledwie kilka tygodni", is_correct: false},
#   {question_id: 22, content: "4-6 miesięcy", is_correct: true},
#   {question_id: 22, content: "3-5 lat", is_correct: false},
#   {question_id: 22, content: "ponad 10 lat", is_correct: false},
#   {question_id: 23, content: "Pantery", is_correct: false},
#   {question_id: 23, content: "Lwy", is_correct: false},
#   {question_id: 23, content: "Tygrysy", is_correct: true},
#   {question_id: 23, content: "Pumy", is_correct: false},
#   {question_id: 24, content: "500 mln lat temu", is_correct: false},
#   {question_id: 24, content: "150 mln lat temu", is_correct: true},
#   {question_id: 24, content: "20 mln lat temu", is_correct: false},
#   {question_id: 24, content: "5 mln lat temu", is_correct: false},
#   {question_id: 25, content: "23°26′ szerokości geograficznej północnej", is_correct: true},
#   {question_id: 25, content: "45° szerokości geograficznej północnej", is_correct: false},
#   {question_id: 25, content: "23°26′ szerokości geograficznej południowej", is_correct: false},
#   {question_id: 25, content: "66°33′ szerokości geograficznej południowej", is_correct: false},
#   {question_id: 26, content: "Nowa Gwinea", is_correct: false},
#   {question_id: 26, content: "Pustynia Gobi", is_correct: false},
#   {question_id: 26, content: "Wyżyna Patagońska", is_correct: false},
#   {question_id: 26, content: "Półwysep Skandynawski", is_correct: true},
#   {question_id: 27, content: "W Ameryce Północnej", is_correct: false},
#   {question_id: 27, content: "W Ameryce Południowej ", is_correct: true},
#   {question_id: 27, content: "W Afryce", is_correct: false},
#   {question_id: 27, content: "W Europoe", is_correct: false}
# ])

# Question.create!([
#   {title: "Jak wysoka jest Wieża Eiffla?"},
#   {title: "Jakie miasto jest stolicą Francji?"},
#   {title: "Jaka rzeka przepływa przez Paryż?"},
#   {title: "Z jakich kolorów składa się flaga Francji?"},
#   {title: "Jaki jest najwyższy szczyt Francji?"},
#   {title: "Jak nazywa się najpopularniejsza na świecie wyszukiwarka internetowa?"},
#   {title: "Jak się nazywa postać z literatury dziecięcej stworzona przez brytyjskiego pisarza A. A. Milne’a."},
#   {title: "Jak brzmi potoczne powiedzenie, które obrazuje gdy ktoś przemyślał coś, zmądrzał lub znalazł wyjście z jakiejś sytuacji?"},
#   {title: "Warzywo znane z dużej zawartości karotenu to:"},
#   {title: "W którym roku odbyła się bitwa pod Grunwaldem?"},
#   {title: "Kto jest autorem Pana Tadeusza?"},
#   {title: "Jak nazywa się zwierzę znane z charakterystycznych białych pasów na czarnej sierści."},
#   {title: "Jak nazywa się najwyższy Polski szczyt?"},
#   {title: "Jak nazywa się znana, niemiecka marka samochodów?"},
#   {title: "Miasto w którym znajduje się słynny most Golden Gate Bridge to?"},
#   {title: "Do jakiej gromady należą Żółwie?"},
#   {title: "Co jest głównym składnikiem diety Pandy wielkiej?"},
#   {title: "Jaka jest długość równika kuli ziemskiej?"},
#   {title: "W jakim morzu znajduje ujście rzeka Jangcy?"},
#   {title: "Ile średnio żyją dzikie (na wolności) myszy?"},
#   {title: "Które z dzikich kotów są największe na świecie?"},
#   {title: "Kiedy pojawiły się na ziemi pierwsze gatunki krokodyli?"},
#   {title: "Na jakiej szerokości geograficznej znajduje się Zwrotnik Raka?"},
#   {title: "Gdzie występuje gatunek Leminga właściwego?"},
#   {title: "Na jakim kontynencie leżą Andy?"}
# ])
# Quiz.create!([
#   {title: "Zaczynamy!", description: "Zapraszamy na pierwszy quiz!", date: "2014-03-09", type: nil, workflow_state: "expired"},
#   {title: "Świat, geografia i zwierzęta", description: "", date: "2014-03-11", type: nil, workflow_state: "active"}
# ])

